# -*- mode: ruby -*-
# vi: set ft=ruby :

$post_script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
CHK_USER=`grep operation /etc/passwd`
if [[ -z $CHK_USER ]]; then
useradd -d /pang operation
mkdir -p ~operation/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjggePUaVLZxoUcvaAixJBPmRLpMIHW/4YQ8eerUFUW98WYvev1iEeu2t7C7XtTdotzVnlK/SvfCArxlf5XsOYctKQ/pwA1ehrrXAMZNNuQmOVvKgNney38VojA1g4/iUTn/1iVg84cuo/1i44qrgkjo815FPfNy+L63Z4Z9+wSPe70Bm5rV8r/55uJ/RbYhFRCIFjpcyztcjcyNWNJ0KJk8AvlOuRCRSqQnzkCxvs+4uNgoly5+zqZs8ewOWXB/I7rlOeGjX26WC90rh6JlsuVdbW9B51AFqS7FOFG1NVZYfE3e6SF9JM+AkFgsdLRgpzXpxL5RpRrX6eL7FP4NPh operation@jenkins" > ~operation/.ssh/authorized_keys
fi
echo "operation     ALL=(ALL)       NOPASSWD: ALL" >> /etc/sudoers
chown -R operation.operation /pang
ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
SCRIPT

Vagrant.configure(2) do |config|
  if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
    config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
  else
    config.vm.synced_folder ".", "/vagrant"
  end
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/trusty64"
    web01.vm.hostname = "web01"
    #web01.vm.network "forwarded_port", guest: 8080, host: 8080
    web01.vm.network "private_network", ip: "10.200.201.21"
    web01.vm.provision "shell", inline: $post_script
    #config.vm.provider "virtualbox" do |vb|
      #vb.customize ["modifyvm", :id, "--cpus", "2"]
      #vb.customize ["modifyvm", :id, "--memory", "8192"]
    #end
  end
  config.vm.define "web02" do |web02|
    web02.vm.box = "ubuntu/trusty64"
    web02.vm.hostname = "web02"
    #web02.vm.network "forwarded_port", guest: 8080, host: 8080
    web02.vm.network "private_network", ip: "10.200.201.22"
    web02.vm.provision "shell", inline: $post_script
    #config.vm.provider "virtualbox" do |vb|
    #vb.customize ["modifyvm", :id, "--cpus", "2"]
    #vb.customize ["modifyvm", :id, "--memory", "8192"]
    #end
  end
  config.vm.define "proxy" do |proxy|
    proxy.vm.box = "ubuntu/trusty64"
    proxy.vm.hostname = "proxy01"
    #proxy.vm.network "forwarded_port", guest: 8080, host: 8080
    proxy.vm.network "private_network", ip: "10.200.201.23"
    proxy.vm.provision "shell", inline: $post_script
    #config.vm.provider "virtualbox" do |vb|
    #vb.customize ["modifyvm", :id, "--cpus", "2"]
    #vb.customize ["modifyvm", :id, "--memory", "8192"]
    #end
  end
end
