---
- hosts: ci
  remote_user: operation

  tasks:
  - name: install java
    yum: name=java state=latest

  - name: copy jenkin.war to target server
    copy:
      src: /Volumes/data/util/
      dest: /pang/jenkins/
      owner: root
      group: root